[build]
  command = "hugo --gc --minify --themesDir ../../"
  base    = "exampleSite"
  publish = "public"

[build.environment]
  HUGO_BASEURL        = "https://skillkeralaonline.netlify.app"
  HUGO_THEME          = "Color Your World"
  HUGO_VERSION        = "0.73.0"
  HUGO_ENABLEGITINFO  = "true"
